#!/usr/bin/env python3
"""Train the hybrid TCS + T-PPR next-snapshot coreness predictor."""

import argparse

from training.ours_training import train


def build_parser():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", help="Directory generated by build_time_slices")
    parser.add_argument("--output", default=None)
    parser.add_argument("--epochs", type=int, default=30)
    parser.add_argument("--patience", type=int, default=5)
    parser.add_argument("--batch-size", type=int, default=128)
    parser.add_argument("--learning-rate", type=float, default=1e-3)
    parser.add_argument("--weight-decay", type=float, default=1e-5)
    parser.add_argument("--train-ratio", type=float, default=0.7)
    parser.add_argument("--val-ratio", type=float, default=0.15)
    parser.add_argument("--max-nodes-per-time", type=int, default=2000)
    parser.add_argument("--top-l", type=int, default=20)
    parser.add_argument("--t-ppr-internal-top-k", type=int, default=20)
    parser.add_argument("--order", type=int, default=4)
    parser.add_argument("--t-ppr-alpha", type=float, default=0.3)
    parser.add_argument("--t-ppr-beta", type=float, default=0.5)
    parser.add_argument("--min-probability", type=float, default=1e-8)
    parser.add_argument("--time-dim", type=int, default=16)
    parser.add_argument("--structure-hidden", type=int, default=64)
    parser.add_argument("--temporal-hidden", type=int, default=64)
    parser.add_argument("--fusion-hidden", type=int, default=128)
    parser.add_argument("--core-dim", type=int, default=32)
    parser.add_argument("--core-lookback", type=int, default=5)
    parser.add_argument("--bucket-dim", type=int, default=16)
    parser.add_argument("--attention-heads", type=int, default=4)
    parser.add_argument("--persistence-scale", type=float, default=2.0)
    parser.add_argument("--ordinal-weight-power", type=float, default=0.5)
    parser.add_argument("--ordinal-weight-cap", type=float, default=10.0)
    parser.add_argument("--dropout", type=float, default=0.2)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--device", default="auto")
    return parser


def main():
    train(build_parser().parse_args())


if __name__ == "__main__":
    main()
